### ISSUE TITLE
Hitting Ctrl+F5 but it just reloads the webpage and nothing happens

### ISSUE THREAD

**Issue by KermitTheFrog4800** [IceHacks/surviv.io#11]
So i am trying to use this my friend can use it just fine but whenever i Hit Ctrl+F5 nothing happens it just reloads the webpage. Here is an image of my settings for Resource Override. https://imgur.com/a/60YNcdA If this helps at all if you need anything else dm me on discord because i am more active on there. Here is name: East_Arctica#1392 Thank you so much if you know how to fix this. 👍

**Comment by KermitTheFrog4800** [comment]
Problem was that i had a space after the url in Resource Override

**Comment by IceHacks** [comment]
Ok. Thank you.
