### ISSUE TITLE
Not working ( Not sure what I did wrong 

### ISSUE THREAD

**Issue by AgaWaga** [IceHacks/surviv.io#3]
I'm stuck. I've done everything you said but when I open Internet explorer or Google chrome nothing happens. http://prntscr.com/jet91i Did I forget anything? I did press ' save ' though but is there anything else I have to do?

**Comment by AgaWaga** [comment]
I just noticed when I launched the game I saw the scope for a split frame. Meaning the script isn't running properly. what could be causing this?

**Comment by IceHacks** [comment]
The script is not loading correctly because Chrome or IE still has the old file in it's cache, please try clearing the cache for Surviv.io. (On FireFox you go to surviv.io and hit `Ctrl`+`F5` I don't know if it is the same for Chrome)

**Comment by IceHacks** [comment]
Thanks for contacting me via Discord, glad this resolved your issue.
