### ISSUE TITLE
Problem with starting

### ISSUE THREAD

**Issue by Budowoja** [IceHacks/surviv.io#5]
The main.js was a website, so I saved the website and put the main.js (website) in my folder.
But when I press "play" nothing happens. 

Sorry for bad english.

**Comment by IceHacks** [comment]
Hello there,
Did you clear the cache? I added that step last night.

**Comment by Budowoja** [comment]
Yep, I did it.

**Comment by Budowoja** [comment]
Doesnt work :(

**Comment by IceHacks** [comment]
Are you using Firefox?

**Comment by Budowoja** [comment]
Yes, Im using Firefox

**Comment by Budowoja** [comment]
Explorer doenst work, too.

**Comment by IceHacks** [comment]
`CTRL` + `F5` should work
