### ISSUE TITLE
keep show update after press play

### ISSUE THREAD

**Issue by jusyin** [IceHacks/surviv.io#6]
![image](https://user-images.githubusercontent.com/39183733/39911740-0722d966-552f-11e8-8616-b1ea9fa38716.png)

hi, i follow the step in your guide but i keep getting this update thing, anyway to fix it?

**Comment by MrChesko** [comment]
just wait 4 an update of hack, don't worry, it'll work

**Comment by DragonflyerHD** [comment]
Hey guys I updated the hack to the newest version. Just switch your main.js file with this one:
https://github.com/DragonflyerHD/surviv.io/tree/master/megamod

Have fun :)
